# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [46]:
'''
a=np.arange(15)
print('list(a):',list(a))
print('a.tolist():',a.tolist())

b=np.arange(15).reshape(3,5)
print('list(b):',list(b))
print('b.tolist():',b.tolist())

list()只能將第一層元素轉換成list，而tolist()則可已將第二層的元素也轉換成list。
'''

"\na=np.arange(15)\nprint('list(a):',list(a))\nprint('a.tolist():',a.tolist())\n\nb=np.arange(15).reshape(3,5)\nprint('list(b):',list(b))\nprint('b.tolist():',b.tolist())\nu \n"

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件

'''
import numpy as np
'''

In [49]:

a = np.random.randint(10, size=6) 

'''
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))
'''

'\nYour Code\n'

In [ ]:
b = np.random.randint(10, size=(3,4)) 

'''
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))
'''

[[0 7 9 3]
 [8 2 7 7]
 [9 3 3 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

'''
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))
'''

[[[1 3]
  [2 8]
  [2 5]]

 [[0 0]
  [8 0]
  [1 6]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [77]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[4, 6, 7, 3, 5, 0]
[4, 6, 7, 3, 5, 0]


In [64]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print([list(b[i]) for i in range(len(b))])


[[1, 9, 9, 2], [0, 5, 6, 8], [5, 4, 2, 5]]
[[1, 9, 9, 2], [0, 5, 6, 8], [5, 4, 2, 5]]


In [88]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))
list(c)

[[[9, 8], [3, 2], [9, 8]], [[5, 9], [3, 2], [8, 7]]]
[array([[9, 8],
       [3, 2],
       [9, 8]]), array([[5, 9],
       [3, 2],
       [8, 7]])]


[array([[9, 8],
        [3, 2],
        [9, 8]]),
 array([[5, 9],
        [3, 2],
        [8, 7]])]

In [ ]:
def tolist(iterable):
    '''
    if type(iterable) != np.ndarray:
        return iterable
    else:
        return [tolist(iterable[i]) for i in range(len(iterable))]
    '''

print(tolist(a))
print(tolist(b))
print(tolist(c))

[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
